title: Mitch Ricker - Automating.Systems
description: My personal GitHub Pages portfolio
url: https://Automating.Systems
###############################
github_name: MitchRicker
github: https://github.com/mitchricker

kofi_name: MitchRicker
kofi: https://ko-fi.com/mitchricker